"""Added origin_tag to all tables

Revision ID: 88d3f8443fdd
Revises: 
Create Date: 2026-06-08 22:02:31.368180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d3f8443fdd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('origin_tag', sa.String(), nullable=True))
    op.create_index(op.f('ix_items_origin_tag'), 'items', ['origin_tag'], unique=False)
    op.add_column('locations', sa.Column('origin_tag', sa.String(), nullable=True))
    op.create_index(op.f('ix_locations_origin_tag'), 'locations', ['origin_tag'], unique=False)
    op.add_column('npcs', sa.Column('origin_tag', sa.String(), nullable=True))
    op.create_index(op.f('ix_npcs_origin_tag'), 'npcs', ['origin_tag'], unique=False)
    op.add_column('players', sa.Column('origin_tag', sa.String(), nullable=True))
    op.create_index(op.f('ix_players_origin_tag'), 'players', ['origin_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_origin_tag'), table_name='players')
    op.drop_column('players', 'origin_tag')
    op.drop_index(op.f('ix_npcs_origin_tag'), table_name='npcs')
    op.drop_column('npcs', 'origin_tag')
    op.drop_index(op.f('ix_locations_origin_tag'), table_name='locations')
    op.drop_column('locations', 'origin_tag')
    op.drop_index(op.f('ix_items_origin_tag'), table_name='items')
    op.drop_column('items', 'origin_tag')
    # ### end Alembic commands ###
