"""auto_update_2026-06-09_00-08-44

Revision ID: cf6b4d381975
Revises: 88d3f8443fdd
Create Date: 2026-06-09 00:08:44.593836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6b4d381975'
down_revision: Union[str, Sequence[str], None] = '88d3f8443fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('equip_slot', sa.String(), nullable=True))
    op.add_column('items', sa.Column('stats', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'stats')
    op.drop_column('items', 'equip_slot')
    # ### end Alembic commands ###
